# Generated by Django 3.2.18 on 2023-06-16 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyingService', '0001_initial'),
        ('planetService', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buying',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_buying', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buying',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_buying', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buying',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planetService.plot'),
        ),
        migrations.AddField(
            model_name='basket',
            name='plot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planetService.plot'),
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
