# Generated by Django 3.2.18 on 2023-06-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('temperature', models.FloatField()),
                ('rotation_speed', models.FloatField()),
                ('diameter', models.FloatField()),
                ('mass', models.FloatField()),
                ('location', models.TextField()),
                ('distance_to_earth', models.FloatField()),
                ('type', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('surface_area', models.FloatField(null=True)),
                ('potential_for_life_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('infrastructure_information', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'planet',
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('area', models.FloatField(null=True)),
                ('price', models.IntegerField(default=0, null=True)),
                ('markUp', models.IntegerField(default=0)),
                ('location', models.TextField(blank=True)),
                ('mesh', models.JSONField()),
                ('isSale', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'plot',
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('temperature', models.FloatField()),
                ('rotation_speed', models.FloatField()),
                ('diameter', models.FloatField()),
                ('mass', models.FloatField()),
                ('location', models.TextField()),
                ('distance_to_earth', models.FloatField()),
                ('type', models.CharField(blank=True, max_length=255)),
                ('age', models.IntegerField()),
                ('luminosity', models.FloatField()),
            ],
            options={
                'db_table': 'star',
            },
        ),
    ]
