# Generated by Django 3.2.18 on 2023-06-07 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('plots_count', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('diameter', models.FloatField(null=True)),
                ('mass', models.FloatField(null=True)),
                ('number_of_satellites', models.IntegerField(null=True)),
                ('surface_area', models.FloatField(null=True)),
                ('potential_for_life_percent', models.BooleanField(default=True)),
                ('available_land_area', models.FloatField(null=True)),
                ('average_land_price', models.IntegerField(null=True)),
                ('infrastructure_information', models.TextField(blank=True)),
                ('location_information', models.TextField(blank=True)),
                ('additional_features', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=7)),
            ],
            options={
                'db_table': 'planet',
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=755, unique=True)),
                ('area', models.FloatField(null=True)),
                ('price', models.IntegerField(default=0, null=True)),
                ('markUp', models.IntegerField(default=0)),
                ('location', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('available_for_sale', models.BooleanField(default=True)),
                ('mesh', models.JSONField()),
                ('color', models.CharField(blank=True, max_length=7)),
                ('isSale', models.BooleanField(default=True)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planetService.planet')),
            ],
            options={
                'db_table': 'plot',
            },
        ),
    ]
