# Generated by Django 3.2.18 on 2023-06-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='potential_for_life_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
