# Generated by Django 3.2.18 on 2023-06-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetService', '0003_planet_plots_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='distance_to_parent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='star',
            name='distance_to_earth',
            field=models.IntegerField(),
        ),
    ]
