# Generated by Django 3.2.18 on 2023-06-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetService', '0004_auto_20230616_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='age',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='star',
            name='luminosity',
            field=models.BigIntegerField(),
        ),
    ]
