# Generated by Django 3.2.18 on 2023-06-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetService', '0005_auto_20230617_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='luminosity',
            field=models.DecimalField(decimal_places=1, max_digits=30),
        ),
    ]
