# Generated by Django 3.2.18 on 2023-06-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetService', '0006_alter_star_luminosity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='star',
            name='luminosity',
            field=models.FloatField(),
        ),
    ]
