# Generated by Django 3.2.18 on 2023-06-16 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planetService', '0007_auto_20230617_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='luminosity',
        ),
    ]
