# Generated by Django 3.2.18 on 2023-06-17 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planetService', '0008_remove_star_luminosity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='distance_to_earth',
        ),
        migrations.AlterField(
            model_name='planet',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planetService.planet'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='star',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planetService.star'),
        ),
    ]
