# Generated by Django 3.2.18 on 2023-06-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetService', '0009_auto_20230617_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='color',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='color',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
