# Generated by Django 3.2.18 on 2023-06-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetService', '0011_alter_planet_distance_to_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='color',
            field=models.CharField(default='#a9a9a9', max_length=7),
        ),
        migrations.AlterField(
            model_name='plot',
            name='color',
            field=models.CharField(default='#a9a9a9', max_length=7),
        ),
    ]
