# Generated by Django 3.2.18 on 2023-06-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userService', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(default='#FF6666', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='logo',
            field=models.TextField(default='mongrol.svg', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegramName',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
    ]
